export const SITE = 'https://www.maholas.com';
export const EMAIL = 'maholascolaboracion@gmail.com';
export const IG = 'https://www.instagram.com/maholasss';
export const TIKTOK = 'https://www.tiktok.com/@maholasss';
export const CREDIT = 'https://gorkadicapitan.com';

// Rutas equivalentes ES <-> EN (para hreflang y el selector de idioma)
export const ROUTES = {
  home: { es: '/', en: '/en' },
  portfolio: { es: '/portfolio', en: '/en/portfolio' },
  about: { es: '/sobre-mi', en: '/en/about' },
  contact: { es: '/contacto', en: '/en/contact' },
};
export const brandPath = (slug, lang) => (lang === 'en' ? `/en/brands/${slug}` : `/marcas/${slug}`);

export function alternates(es, en, lang) {
  return {
    canonical: SITE + (lang === 'en' ? en : es),
    languages: { es: SITE + es, en: SITE + en, 'x-default': SITE + es },
  };
}

export const T = {
  es: {
    nav: { portfolio: 'Portfolio', about: 'Sobre mí', contact: 'Contacto', cta: 'Trabajemos juntas', other: 'EN', otherLabel: 'English' },
    heroEyebrow: 'Creadora UGC · Bailarina profesional',
    heroH1: 'Creadora de contenido UGC de beauty, moda y lifestyle',
    heroSub: 'Grabo vídeos para marcas desde mi día a día: rutinas de skincare, GRWM, try-ons y hauls. Contenido que parece de una amiga y está pensado para vender en TikTok, Reels y anuncios.',
    heroCta: 'Ver portfolio',
    heroCta2: 'Escríbeme',
    stats: [['+25', 'marcas'], ['9:16', 'vídeo vertical'], ['ES · EN', 'idiomas']],
    trusted: 'Marcas con las que he trabajado',
    whatEyebrow: 'Qué hago',
    whatH2: 'Contenido que la gente no pasa de largo.',
    whatP: 'El UGC funciona porque no parece un anuncio. Yo lo grabo igual que grabo mi vida, pero con un guion detrás y un objetivo claro para tu marca.',
    what: [
      ['Vídeos UGC para anuncios', 'Hook en los primeros segundos, beneficio claro y cierre con llamada a la acción. Listos para Meta y TikTok Ads.'],
      ['Rutinas, GRWM y reseñas', 'Skincare y maquillaje contados en primera persona, con la textura y el resultado a la vista.'],
      ['Try-ons, hauls y unboxing', 'Moda y producto en movimiento, del paquete a la calle.'],
      ['Baile y tendencias', 'Soy bailarina. Si tu marca quiere entrar en una tendencia con ritmo, aquí se nota.'],
    ],
    stepsH: 'Cómo trabajamos',
    steps: [['Brief', 'Me cuentas el producto, el público y dónde se va a publicar.'], ['Guion', 'Te propongo hooks y estructura antes de grabar.'], ['Grabación', 'Con mi luz, mis espacios y mi forma de contar.'], ['Entrega', 'Vídeo vertical editado, con las versiones que acordemos.']],
    zzEyebrow: 'Trabajos',
    zzH2: 'Algunas marcas, contadas a mi manera.',
    zzLink: 'Ver trabajo',
    aboutEyebrow: 'Sobre mí',
    aboutH2: 'Bailarina antes que creadora.',
    aboutP: 'Soy Mahola. Del baile me traigo el ritmo, la expresión y la costumbre de repetir una toma hasta que sale bien. Eso es lo que hace que un vídeo de quince segundos se vea hasta el final.',
    aboutLink: 'Conóceme',
    ctaH2: '¿Tienes un producto que contar?',
    ctaP: 'Cuéntame qué necesitas y te respondo yo misma.',
    ctaBtn: 'Escríbeme',
    footer: { tagline: 'Creadora de contenido UGC y bailarina profesional.', rights: 'Todos los derechos reservados', by: 'Fotografía, vídeo y web por' },
    portfolioEyebrow: 'Portfolio UGC',
    portfolioH1: 'Trabajos UGC por marca',
    portfolioP: 'Pasa el ratón por encima de cada marca para ver el vídeo. Haz clic para verlo con sonido.',
    all: 'Todas',
    close: 'Cerrar',
    prev: 'Anterior',
    next: 'Siguiente',
    sound: 'Toca para activar el sonido',
    otherBrands: 'Otras marcas',
    brandH1: (n) => `Contenido UGC para ${n}`,
    contactH1: 'Trabajemos juntas',
    contactP: 'Para colaboraciones, campañas UGC o contenido para anuncios, escríbeme. Respondo yo, normalmente en uno o dos días.',
    form: { name: 'Tu nombre', brand: 'Marca o agencia', msg: 'Qué necesitas', send: 'Enviar por email', note: 'Se abrirá tu correo con el mensaje ya escrito.' },
    aboutH1: 'Bailarina profesional y creadora de contenido',
  },
  en: {
    nav: { portfolio: 'Portfolio', about: 'About', contact: 'Contact', cta: "Let's work together", other: 'ES', otherLabel: 'Español' },
    heroEyebrow: 'UGC creator · Professional dancer',
    heroH1: 'UGC content creator for beauty, fashion and lifestyle',
    heroSub: 'I film videos for brands from my everyday life: skincare routines, GRWMs, try-ons and hauls. Content that feels like a friend’s and is built to sell on TikTok, Reels and paid ads.',
    heroCta: 'See portfolio',
    heroCta2: 'Get in touch',
    stats: [['25+', 'brands'], ['9:16', 'vertical video'], ['ES · EN', 'languages']],
    trusted: 'Brands I have worked with',
    whatEyebrow: 'What I do',
    whatH2: 'Content people don’t scroll past.',
    whatP: 'UGC works because it doesn’t look like an ad. I film it the way I film my life, with a script behind it and a clear goal for your brand.',
    what: [
      ['UGC video ads', 'A hook in the first seconds, a clear benefit and a call to action. Ready for Meta and TikTok Ads.'],
      ['Routines, GRWMs and reviews', 'Skincare and makeup told first-hand, with texture and results on show.'],
      ['Try-ons, hauls and unboxings', 'Fashion and products in motion, from the parcel to the street.'],
      ['Dance and trends', 'I’m a dancer. If your brand wants to jump on a trend with rhythm, it shows.'],
    ],
    stepsH: 'How we work',
    steps: [['Brief', 'You tell me about the product, the audience and where it will run.'], ['Script', 'I suggest hooks and structure before filming.'], ['Filming', 'My light, my spaces and my way of telling it.'], ['Delivery', 'Edited vertical video, with the versions we agree on.']],
    zzEyebrow: 'Work',
    zzH2: 'A few brands, told my way.',
    zzLink: 'See the work',
    aboutEyebrow: 'About',
    aboutH2: 'A dancer before a creator.',
    aboutP: 'I’m Mahola. From dance I bring rhythm, expression and the habit of repeating a take until it’s right. That’s what makes people watch a fifteen-second video to the end.',
    aboutLink: 'Meet me',
    ctaH2: 'Got a product to talk about?',
    ctaP: 'Tell me what you need and I’ll reply myself.',
    ctaBtn: 'Get in touch',
    footer: { tagline: 'UGC content creator and professional dancer.', rights: 'All rights reserved', by: 'Photography, video and website by' },
    portfolioEyebrow: 'UGC portfolio',
    portfolioH1: 'UGC work by brand',
    portfolioP: 'Hover over each brand to see the video. Click to watch it with sound.',
    all: 'All',
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
    sound: 'Tap for sound',
    otherBrands: 'Other brands',
    brandH1: (n) => `UGC content for ${n}`,
    contactH1: "Let's work together",
    contactP: 'For collaborations, UGC campaigns or content for ads, drop me a line. I reply myself, usually within a day or two.',
    form: { name: 'Your name', brand: 'Brand or agency', msg: 'What you need', send: 'Send by email', note: 'Your email app will open with the message ready.' },
    aboutH1: 'Professional dancer and content creator',
  },
};
