export const SITE = 'https://www.maholas.com';
export const EMAIL = 'maholascolaboracion@gmail.com';
export const IG = 'https://www.instagram.com/maholasss';
export const TIKTOK = 'https://www.tiktok.com/@maholasss';
export const YOUTUBE = 'https://www.youtube.com/@maholasss';
export const FACEBOOK = 'https://www.facebook.com/jeniffer.altunaga';
export const CREDIT = 'https://gorkadicapitan.com';

// Rutas equivalentes ES <-> EN (para hreflang y el selector de idioma)
export const ROUTES = {
  home: { es: '/', en: '/en' },
  portfolio: { es: '/portfolio', en: '/en/portfolio' },
  about: { es: '/sobre-mi', en: '/en/about' },
  contact: { es: '/contacto', en: '/en/contact' },
};
export const brandPath = (slug, lang) => (lang === 'en' ? `/en/brands/${slug}` : `/marcas/${slug}`);

export function alternates(es, en, lang) {
  return {
    canonical: SITE + (lang === 'en' ? en : es),
    languages: { es: SITE + es, en: SITE + en, 'x-default': SITE + es },
  };
}

export const T = {
  es: {
    nav: { portfolio: 'Portfolio', about: 'Sobre mí', contact: 'Contacto', cta: 'Trabajemos juntas', other: 'EN', otherLabel: 'English' },
    heroEyebrow: 'Creadora de contenido en Valencia · @maholasss',
    heroH1: 'Creadora de contenido en Valencia: beauty, moda y lifestyle',
    heroSub: 'Vídeos y fotos para marcas de beauty, skincare, moda, perfume y lifestyle: para tus redes, tus lanzamientos y tus anuncios. No enseño un producto, construyo una historia alrededor de él.',
    heroCta: 'Ver portfolio',
    heroCta2: 'Pedir presupuesto',
    stats: [['+60', 'campañas'], ['19,7 K', 'en Instagram · sep 2026'], ['+32 K', 'en todas sus redes']],
    trusted: 'Marcas con las que he trabajado',
    whatEyebrow: 'Qué hago',
    reach: 'Trabajo con marcas de cualquier país. Me mandan el producto, grabo desde Valencia o la Costa del Sol y, si el proyecto lo pide, viajo a donde haga falta.',
    whatPlain: 'Se puede contratar de dos formas. Contenido para la marca: la marca me manda el producto, yo grabo el vídeo (y las fotos, si hacen falta) y lo entrego listo para sus redes y sus anuncios. O colaboración en mi perfil: la pieza se publica en mis redes, con mi audiencia. Se pueden combinar.',
    whatH2: 'Contenido que la gente\nno pasa de largo.',
    whatP: 'No quiero hacer contenido que parezca un anuncio, sino contenido que la gente vea porque lo cuento yo. Juego con el outfit, el maquillaje, la actitud y el escenario hasta que tu marca es parte de la historia.',
    what: [
      ['Vídeos para anuncios', 'Hook en los primeros segundos, beneficio claro y cierre con llamada a la acción. Listos para Meta y TikTok Ads.'],
      ['Rutinas, GRWM y reseñas', 'Skincare y maquillaje contados en primera persona, con la textura y el resultado a la vista.'],
      ['Try-ons, hauls y unboxing', 'Moda y producto en movimiento, del paquete a la calle.'],
      ['Baile y tendencias', 'Vengo de la danza y de años de formación artística: expresión, movimiento e interpretación delante de la cámara.'],
    ],
    packsH2: 'Qué puedes contratar',
    packsP: 'Sin packs cerrados: el presupuesto sale del número de piezas, las versiones y dónde se va a usar.',
    packs: [
      ['UGC para tus redes', 'Reels, TikToks y stories con el producto en mi día a día, entregados para que los publiques en tus canales.'],
      ['UGC para anuncios', 'Piezas de 6 a 30 segundos con hook, beneficio y cierre, en varias versiones para probar. Con derechos de uso en paid.'],
      ['Colaboración en mi perfil', 'La pieza sale en mis redes, con mi audiencia, en español o en inglés. Puntual o como embajadora.'],
      ['Fotos de producto y retrato', 'Stills y fotos conmigo y el producto para web, ficha de tienda y redes. En casa o con fotógrafo, según la campaña.'],
      ['Pack mensual', 'Un número fijo de piezas al mes para marcas que necesitan contenido constante, con calendario y entregas cerradas.'],
    ],
    stepsH: 'Cómo trabajamos',
    steps: [['Brief', 'Me cuentas el producto, el público y dónde se va a publicar.'], ['Guion', 'Te propongo hooks y estructura antes de grabar.'], ['Grabación', 'En casa o en estudio, según lo que pida la campaña.'], ['Entrega', 'Desde 7 días contando desde que me llega el producto.']],
    zzEyebrow: 'Trabajos',
    zzH2: 'Algunas marcas, contadas a mi manera.',
    zzLink: 'Ver trabajo',
    aboutEyebrow: 'Sobre mí',
    aboutH2: 'Creadora de contenido, con el baile detrás.',
    aboutP: 'Soy Mahola. No quiero que una marca vea mi perfil y piense “es una chica que hace UGC”, sino “me gusta cómo cuenta las cosas, a ver qué haría con lo nuestro”.',
    aboutLink: 'Conóceme',
    ctaH2: '¿Hacemos algo con tu marca?',
    ctaP: 'Cuéntame el producto y lo que necesitas. Te contesto yo, con presupuesto, en uno o dos días.',
    ctaBtn: 'Pedir presupuesto',
    footer: { tagline: 'Creadora de contenido y bailarina profesional. @maholasss en todas las redes.', rights: 'Todos los derechos reservados', by: 'Fotografía, vídeo y web por' },
    portfolioEyebrow: 'Portfolio',
    portfolioH1: 'Trabajos por marca',
    portfolioP: 'Entra en cada marca y verás sus vídeos, con sonido, y lo que hicimos juntas.',
    picksH2: 'Cuatro piezas para empezar',
    filtersH: 'Filtra por categoría',
    picks: { 'huda-beauty': 'Dirección visual y personaje', cerave: 'Rutina contada a cámara', shein: 'Try-on con ritmo', 'loreal-paris': 'GRWM de maquillaje', mugler: 'Perfume en plano corto', lancome: 'Reacción a un lanzamiento' },
    modos: { marca: 'Contenido entregado a la marca', perfil: 'Publicado en el perfil de Mahola', ambos: 'Para la marca y en el perfil de Mahola' },
    all: 'Todas',
    close: 'Cerrar',
    prev: 'Anterior',
    next: 'Siguiente',
    sound: 'Toca para activar el sonido',
    otherBrands: 'Otras marcas',
    brandVids: 'Los vídeos',
    photoBy: 'Fotografía:',
    videoBy: 'Vídeo:',
    facts: { campaigns: 'Campañas', since: 'Desde', videos: 'Vídeos aquí', tipo: 'Relación', modo: 'Modalidad', fav: 'Mi favorita' },
    wallH2: 'Las marcas',
    backToPortfolio: 'Volver al portfolio',
    video: 'vídeo',
    videos: 'vídeos',
    brandH1: (n) => `Vídeos para ${n}`,
    contactH1: 'Trabajemos juntas',
    contactP: 'Para colaboraciones, campañas o contenido para anuncios, escríbeme. Respondo yo. Trabajo con marcas de cualquier país, grabo en español y en inglés y entrego desde 7 días.',
    form: { name: 'Tu nombre', email: 'Tu email', brand: 'Marca o agencia', optional: 'opcional', sector: 'Sector', sectors: ['Beauty y skincare', 'Maquillaje', 'Moda', 'Perfume', 'Pelo', 'Fitness', 'Lifestyle', 'Otro'], goal: 'Qué buscas', goals: ['UGC para mis redes', 'UGC para anuncios', 'Colaboración en el perfil de Mahola', 'Fotos de producto', 'Pack mensual', 'Aún no lo sé'], when: 'Para cuándo', whens: ['Esta semana', 'Este mes', 'En uno o dos meses', 'Sin fecha'], budget: 'Presupuesto orientativo', budgets: ['Menos de 300 €', '300 a 800 €', '800 a 2.000 €', 'Más de 2.000 €', 'Prefiero que me lo propongas'], msg: 'Cuéntame más', msgHint: 'Producto, número de piezas, fecha y dónde se va a usar.', send: 'Enviar', sending: 'Enviando…', note: 'Te contesto yo, normalmente en uno o dos días.', privacy: 'Solo uso tus datos para responderte.', privacyLink: 'Privacidad', ok: 'Recibido, gracias.', okSub: 'Te contesto en uno o dos días al correo que me has dejado.', errorNote: 'No he podido enviarlo desde aquí: te he abierto el correo con el mensaje escrito.' },
    aboutH1: 'Creadora de contenido en Valencia, bailarina de formación',
    faqH2: 'Preguntas frecuentes',
    faq: [
      ['¿Solo trabajas con marcas de Valencia?', 'No. Trabajo con marcas de cualquier país: me envían el producto y grabo desde Valencia o la Costa del Sol. Si el proyecto lo requiere, viajo.'],
      ['¿Cuánto tardas en entregar?', 'Desde 7 días, contando desde que me llega el producto.'],
      ['¿En qué idiomas grabas?', 'Español e inglés.'],
      ['¿Qué se puede contratar?', 'Dos cosas, y se pueden combinar: contenido que entrego a la marca para sus canales, o una colaboración publicada en mis perfiles.'],
      ['¿Cuánto cuesta?', 'Depende del número de piezas, de las versiones y subtítulos que hagan falta, de si se publica en mi perfil y de si la marca va a usar el contenido en anuncios. Escríbeme y te paso presupuesto cerrado.'],
      ['¿Grabas tú sola?', 'Casi siempre sí. Cuando la campaña pide un acabado más comercial, trabajo con un fotógrafo.'],
      ['¿Qué tipo de marcas?', 'Beauty y skincare sobre todo, y también moda, perfume, pelo y lifestyle.'],
    ],
  },
  en: {
    nav: { portfolio: 'Portfolio', about: 'About', contact: 'Contact', cta: "Let's work together", other: 'ES', otherLabel: 'Español' },
    heroEyebrow: 'Content creator based in Valencia · @maholasss',
    heroH1: 'Content creator in Valencia: beauty, fashion and lifestyle',
    heroSub: 'Videos and photos for beauty, skincare, fashion, fragrance and lifestyle brands: for your feeds, your launches and your ads. I don’t just show a product, I build a story around it.',
    heroCta: 'See portfolio',
    heroCta2: 'Ask for a quote',
    stats: [['60+', 'campaigns'], ['19.7 K', 'on Instagram · Sep 2026'], ['32 K+', 'across all channels']],
    trusted: 'Brands I have worked with',
    whatEyebrow: 'What I do',
    reach: 'I work with brands anywhere in the world. You ship me the product, I film from Valencia or the Costa del Sol and, if the project calls for it, I travel wherever it needs me.',
    whatPlain: 'There are two ways to work with me. Content for the brand: you send me the product, I film the video (and shoot the photos if needed) and hand it over ready for your feeds and ads. Or a collaboration on my profile: the piece goes out on my channels, to my audience. Both can be combined.',
    whatH2: 'Content people\ndon’t scroll past.',
    whatP: 'I don’t want to make content that looks like an ad, but content people watch because I’m the one telling it. I play with the outfit, the makeup, the attitude and the setting until your brand is part of the story.',
    what: [
      ['Videos for ads', 'A hook in the first seconds, a clear benefit and a call to action. Ready for Meta and TikTok Ads.'],
      ['Routines, GRWMs and reviews', 'Skincare and makeup told first-hand, with texture and results on show.'],
      ['Try-ons, hauls and unboxings', 'Fashion and products in motion, from the parcel to the street.'],
      ['Dance and trends', 'I come from dance and years of artistic training: expression, movement and performance in front of the camera.'],
    ],
    packsH2: 'What you can hire',
    packsP: 'No fixed bundles: the quote comes from the number of pieces, the versions and where they will run.',
    packs: [
      ['UGC for your feeds', 'Reels, TikToks and stories with the product in my everyday life, delivered for you to post on your own channels.'],
      ['UGC for ads', '6 to 30 second pieces with a hook, a benefit and a close, in several versions to test. Paid usage rights included.'],
      ['Collaboration on my profile', 'The piece goes out on my channels, to my audience, in Spanish or English. One-off or as an ambassador.'],
      ['Product and portrait photos', 'Stills and photos of me with the product for your website, product pages and social. At home or with a photographer, depending on the campaign.'],
      ['Monthly pack', 'A fixed number of pieces a month for brands that need constant content, with a calendar and closed deliveries.'],
    ],
    stepsH: 'How we work',
    steps: [['Brief', 'You tell me about the product, the audience and where it will run.'], ['Script', 'I suggest hooks and structure before filming.'], ['Filming', 'At home or in a studio, whatever the campaign calls for.'], ['Delivery', 'From 7 days, counting from the moment the product reaches me.']],
    zzEyebrow: 'Work',
    zzH2: 'A few brands, told my way.',
    zzLink: 'See the work',
    aboutEyebrow: 'About',
    aboutH2: 'A content creator, with dance behind it.',
    aboutP: 'I’m Mahola. I don’t want a brand to look at my profile and think “a girl who makes UGC”, but “I like how she tells things, let’s see what she’d do with ours”.',
    aboutLink: 'Meet me',
    ctaH2: 'Shall we do something with your brand?',
    ctaP: 'Tell me about the product and what you need. I reply myself, with a quote, within a day or two.',
    ctaBtn: 'Ask for a quote',
    footer: { tagline: 'Content creator and professional dancer. @maholasss on every channel.', rights: 'All rights reserved', by: 'Photography, video and website by' },
    portfolioEyebrow: 'Portfolio',
    portfolioH1: 'Work by brand',
    portfolioP: 'Open a brand to see its videos, with sound, and what we did together.',
    picksH2: 'Four pieces to start with',
    filtersH: 'Filter by category',
    picks: { 'huda-beauty': 'Art direction and character', cerave: 'A routine told to camera', shein: 'Try-on with rhythm', 'loreal-paris': 'Makeup GRWM', mugler: 'Fragrance in close-up', lancome: 'Reacting to a launch' },
    modos: { marca: 'Content delivered to the brand', perfil: 'Published on Mahola’s profile', ambos: 'For the brand and on Mahola’s profile' },
    all: 'All',
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
    sound: 'Tap for sound',
    otherBrands: 'Other brands',
    brandVids: 'The videos',
    photoBy: 'Photography:',
    videoBy: 'Video:',
    facts: { campaigns: 'Campaigns', since: 'Since', videos: 'Videos here', tipo: 'Relationship', modo: 'Format', fav: 'My favourite' },
    wallH2: 'The brands',
    backToPortfolio: 'Back to portfolio',
    video: 'video',
    videos: 'videos',
    brandH1: (n) => `Videos for ${n}`,
    contactH1: "Let's work together",
    contactP: 'For collaborations, campaigns or content for ads, drop me a line. I reply myself. I work with brands from any country, film in Spanish and English and deliver from 7 days.',
    form: { name: 'Your name', email: 'Your email', brand: 'Brand or agency', optional: 'optional', sector: 'Sector', sectors: ['Beauty and skincare', 'Makeup', 'Fashion', 'Fragrance', 'Haircare', 'Fitness', 'Lifestyle', 'Other'], goal: 'What you are after', goals: ['UGC for our feeds', 'UGC for ads', 'A collaboration on Mahola’s profile', 'Product photos', 'Monthly pack', 'Not sure yet'], when: 'When', whens: ['This week', 'This month', 'In one or two months', 'No date yet'], budget: 'Rough budget', budgets: ['Under €300', '€300 to €800', '€800 to €2,000', 'Over €2,000', 'I’d rather you propose'], msg: 'Tell me more', msgHint: 'Product, number of pieces, timing and where it will run.', send: 'Send', sending: 'Sending…', note: 'I reply myself, usually within a day or two.', privacy: 'I only use your details to reply to you.', privacyLink: 'Privacy', ok: 'Got it, thank you.', okSub: 'I’ll reply within a day or two to the address you left.', errorNote: 'I couldn’t send it from here: I’ve opened your email app with the message ready.' },
    aboutH1: 'Content creator in Valencia, dancer by training',
    faqH2: 'Frequently asked',
    faq: [
      ['Do you only work with brands in Valencia?', 'No. I work with brands from any country: you ship me the product and I film from Valencia or the Costa del Sol. If the project requires it, I travel.'],
      ['How long does delivery take?', 'From 7 days, counting from the moment the product reaches me.'],
      ['Which languages do you film in?', 'Spanish and English.'],
      ['What can I hire?', 'Two things, and they combine: content I deliver to the brand for its own channels, or a collaboration published on my profiles.'],
      ['What does it cost?', 'It depends on the number of pieces, the versions and subtitles needed, whether it goes out on my profile and whether the brand will use it in paid ads. Write to me and I’ll send a fixed quote.'],
      ['Do you film everything yourself?', 'Almost always. When a campaign needs a more commercial finish, I work with a photographer.'],
      ['What kind of brands?', 'Beauty and skincare above all, plus fashion, fragrance, haircare and lifestyle.'],
    ],
  },
};
