export const SITE = 'https://www.maholas.com';
export const EMAIL = 'maholascolaboracion@gmail.com';
export const IG = 'https://www.instagram.com/maholasss';
export const TIKTOK = 'https://www.tiktok.com/@maholasss';
export const YOUTUBE = 'https://www.youtube.com/@maholasss';
export const FACEBOOK = 'https://www.facebook.com/jeniffer.altunaga';
export const CREDIT = 'https://gorkadicapitan.com';

// Rutas equivalentes ES <-> EN (para hreflang y el selector de idioma)
export const ROUTES = {
  home: { es: '/', en: '/en' },
  portfolio: { es: '/portfolio', en: '/en/portfolio' },
  about: { es: '/sobre-mi', en: '/en/about' },
  contact: { es: '/contacto', en: '/en/contact' },
};
export const brandPath = (slug, lang) => (lang === 'en' ? `/en/brands/${slug}` : `/marcas/${slug}`);

export function alternates(es, en, lang) {
  return {
    canonical: SITE + (lang === 'en' ? en : es),
    languages: { es: SITE + es, en: SITE + en, 'x-default': SITE + es },
  };
}

export const T = {
  es: {
    nav: { portfolio: 'Portfolio', about: 'Sobre mí', contact: 'Contacto', cta: 'Trabajemos juntas', other: 'EN', otherLabel: 'English' },
    heroEyebrow: 'Creadora de contenido en Valencia',
    heroH1: 'Creadora de contenido en Valencia: beauty, moda y lifestyle',
    heroSub: 'No enseño un producto: construyo una historia alrededor de él. Más de 60 campañas de beauty, moda, perfume y lifestyle.',
    heroCta: 'Ver portfolio',
    heroCta2: 'Pedir presupuesto',
    stats: [['+60', 'campañas'], ['+32 K', 'seguidores en IG y TikTok'], ['2019', 'creando contenido']],
    trusted: 'Marcas con las que he trabajado',
    whatEyebrow: 'Qué hago',
    whatPlain: 'Se puede contratar de dos formas. Contenido para la marca: la marca me manda el producto, yo grabo el vídeo (y las fotos, si hacen falta) y lo entrego listo para sus redes y sus anuncios. O colaboración en mi perfil: la pieza se publica en mis redes, con mi audiencia. Se pueden combinar.',
    whatH2: 'Contenido que la gente no pasa de largo.',
    whatP: 'No quiero hacer contenido que parezca un anuncio, sino contenido que la gente vea porque lo cuento yo. Juego con el outfit, el maquillaje, la actitud y el escenario hasta que tu marca es parte de la historia.',
    what: [
      ['Vídeos para anuncios', 'Hook en los primeros segundos, beneficio claro y cierre con llamada a la acción. Listos para Meta y TikTok Ads.'],
      ['Rutinas, GRWM y reseñas', 'Skincare y maquillaje contados en primera persona, con la textura y el resultado a la vista.'],
      ['Try-ons, hauls y unboxing', 'Moda y producto en movimiento, del paquete a la calle.'],
      ['Baile y tendencias', 'Vengo de la danza y de años de formación artística: expresión, movimiento e interpretación delante de la cámara.'],
    ],
    stepsH: 'Cómo trabajamos',
    steps: [['Brief', 'Me cuentas el producto, el público y dónde se va a publicar.'], ['Guion', 'Te propongo hooks y estructura antes de grabar.'], ['Grabación', 'En casa o en estudio, según lo que pida la campaña.'], ['Entrega', 'Desde 7 días contando desde que me llega el producto.']],
    zzEyebrow: 'Trabajos',
    zzH2: 'Algunas marcas, contadas a mi manera.',
    zzLink: 'Ver trabajo',
    aboutEyebrow: 'Sobre mí',
    aboutH2: 'Creadora de contenido, con el baile detrás.',
    aboutP: 'Soy Mahola. No quiero que una marca vea mi perfil y piense “es una chica que hace UGC”, sino “me gusta cómo cuenta las cosas, a ver qué haría con lo nuestro”.',
    aboutLink: 'Conóceme',
    ctaH2: '¿Tienes un producto que contar?',
    ctaP: 'Cuéntame qué necesitas y te respondo yo misma.',
    ctaBtn: 'Pedir presupuesto',
    footer: { tagline: 'Creadora de contenido y bailarina profesional.', rights: 'Todos los derechos reservados', by: 'Fotografía, vídeo y web por' },
    portfolioEyebrow: 'Portfolio',
    portfolioH1: 'Trabajos por marca',
    portfolioP: 'Entra en cada marca y verás sus vídeos, con sonido, y lo que hicimos juntas.',
    picksH2: 'Tres piezas para empezar',
    picks: { 'huda-beauty': 'Dirección visual y personaje', cerave: 'Rutina contada a cámara', shein: 'Try-on con ritmo' },
    all: 'Todas',
    close: 'Cerrar',
    prev: 'Anterior',
    next: 'Siguiente',
    sound: 'Toca para activar el sonido',
    otherBrands: 'Otras marcas',
    brandVids: 'Los vídeos',
    photoBy: 'Fotografía:',
    videoBy: 'Vídeo:',
    facts: { campaigns: 'Campañas', since: 'Desde', videos: 'Vídeos aquí', tipo: 'Relación', fav: 'Mi favorita' },
    wallH2: 'Las marcas',
    backToPortfolio: 'Volver al portfolio',
    video: 'vídeo',
    videos: 'vídeos',
    brandH1: (n) => `Vídeos para ${n}`,
    contactH1: 'Trabajemos juntas',
    contactP: 'Para colaboraciones, campañas o contenido para anuncios, escríbeme. Respondo yo. Grabo en español y en inglés, salgo de Valencia cuando hace falta y entrego desde 7 días.',
    form: { name: 'Tu nombre', email: 'Tu email', brand: 'Marca o agencia', optional: 'opcional', msg: 'Qué necesitas', msgHint: 'Producto, número de piezas, fecha y dónde se va a usar.', send: 'Enviar', sending: 'Enviando…', note: 'Te contesto yo, normalmente en uno o dos días.', privacy: 'Solo uso tus datos para responderte.', privacyLink: 'Privacidad', ok: 'Recibido, gracias.', okSub: 'Te contesto en uno o dos días al correo que me has dejado.', errorNote: 'No he podido enviarlo desde aquí: te he abierto el correo con el mensaje escrito.' },
    aboutH1: 'Creadora de contenido en Valencia, bailarina de formación',
    faqH2: 'Preguntas frecuentes',
    faq: [
      ['¿Dónde estás y te mueves fuera?', 'Vivo en Valencia y trabajo en toda España. Si la campaña lo pide, viajo.'],
      ['¿Cuánto tardas en entregar?', 'Desde 7 días, contando desde que me llega el producto.'],
      ['¿En qué idiomas grabas?', 'Español e inglés.'],
      ['¿Qué se puede contratar?', 'Dos cosas, y se pueden combinar: contenido que entrego a la marca para sus canales, o una colaboración publicada en mis perfiles.'],
      ['¿Cuánto cuesta?', 'Depende del número de piezas, de las versiones y subtítulos que hagan falta, de si se publica en mi perfil y de si la marca va a usar el contenido en anuncios. Escríbeme y te paso presupuesto cerrado.'],
      ['¿Grabas tú sola?', 'Casi siempre sí. Cuando la campaña pide un acabado más comercial, trabajo con un fotógrafo.'],
      ['¿Qué tipo de marcas?', 'Beauty y skincare sobre todo, y también moda, perfume, pelo y lifestyle.'],
    ],
  },
  en: {
    nav: { portfolio: 'Portfolio', about: 'About', contact: 'Contact', cta: "Let's work together", other: 'ES', otherLabel: 'Español' },
    heroEyebrow: 'Content creator based in Valencia',
    heroH1: 'Content creator in Valencia: beauty, fashion and lifestyle',
    heroSub: 'I don’t just show a product: I build a story around it. More than 60 campaigns in beauty, fashion, fragrance and lifestyle.',
    heroCta: 'See portfolio',
    heroCta2: 'Ask for a quote',
    stats: [['60+', 'campaigns'], ['32 K+', 'followers on IG & TikTok'], ['2019', 'creating']],
    trusted: 'Brands I have worked with',
    whatEyebrow: 'What I do',
    whatPlain: 'There are two ways to work with me. Content for the brand: you send me the product, I film the video (and shoot the photos if needed) and hand it over ready for your feeds and ads. Or a collaboration on my profile: the piece goes out on my channels, to my audience. Both can be combined.',
    whatH2: 'Content people don’t scroll past.',
    whatP: 'I don’t want to make content that looks like an ad, but content people watch because I’m the one telling it. I play with the outfit, the makeup, the attitude and the setting until your brand is part of the story.',
    what: [
      ['Videos for ads', 'A hook in the first seconds, a clear benefit and a call to action. Ready for Meta and TikTok Ads.'],
      ['Routines, GRWMs and reviews', 'Skincare and makeup told first-hand, with texture and results on show.'],
      ['Try-ons, hauls and unboxings', 'Fashion and products in motion, from the parcel to the street.'],
      ['Dance and trends', 'I come from dance and years of artistic training: expression, movement and performance in front of the camera.'],
    ],
    stepsH: 'How we work',
    steps: [['Brief', 'You tell me about the product, the audience and where it will run.'], ['Script', 'I suggest hooks and structure before filming.'], ['Filming', 'At home or in a studio, whatever the campaign calls for.'], ['Delivery', 'From 7 days, counting from the moment the product reaches me.']],
    zzEyebrow: 'Work',
    zzH2: 'A few brands, told my way.',
    zzLink: 'See the work',
    aboutEyebrow: 'About',
    aboutH2: 'A content creator, with dance behind it.',
    aboutP: 'I’m Mahola. I don’t want a brand to look at my profile and think “a girl who makes UGC”, but “I like how she tells things, let’s see what she’d do with ours”.',
    aboutLink: 'Meet me',
    ctaH2: 'Got a product to talk about?',
    ctaP: 'Tell me what you need and I’ll reply myself.',
    ctaBtn: 'Ask for a quote',
    footer: { tagline: 'Content creator and professional dancer.', rights: 'All rights reserved', by: 'Photography, video and website by' },
    portfolioEyebrow: 'Portfolio',
    portfolioH1: 'Work by brand',
    portfolioP: 'Open a brand to see its videos, with sound, and what we did together.',
    picksH2: 'Three pieces to start with',
    picks: { 'huda-beauty': 'Art direction and character', cerave: 'A routine told to camera', shein: 'Try-on with rhythm' },
    all: 'All',
    close: 'Close',
    prev: 'Previous',
    next: 'Next',
    sound: 'Tap for sound',
    otherBrands: 'Other brands',
    brandVids: 'The videos',
    photoBy: 'Photography:',
    videoBy: 'Video:',
    facts: { campaigns: 'Campaigns', since: 'Since', videos: 'Videos here', tipo: 'Relationship', fav: 'My favourite' },
    wallH2: 'The brands',
    backToPortfolio: 'Back to portfolio',
    video: 'video',
    videos: 'videos',
    brandH1: (n) => `Videos for ${n}`,
    contactH1: "Let's work together",
    contactP: 'For collaborations, campaigns or content for ads, drop me a line. I reply myself. I film in Spanish and English, travel outside Valencia when needed and deliver from 7 days.',
    form: { name: 'Your name', email: 'Your email', brand: 'Brand or agency', optional: 'optional', msg: 'What you need', msgHint: 'Product, number of pieces, timing and where it will run.', send: 'Send', sending: 'Sending…', note: 'I reply myself, usually within a day or two.', privacy: 'I only use your details to reply to you.', privacyLink: 'Privacy', ok: 'Got it, thank you.', okSub: 'I’ll reply within a day or two to the address you left.', errorNote: 'I couldn’t send it from here: I’ve opened your email app with the message ready.' },
    aboutH1: 'Content creator in Valencia, dancer by training',
    faqH2: 'Frequently asked',
    faq: [
      ['Where are you, and do you travel?', 'I live in Valencia and work across Spain. If the campaign calls for it, I travel.'],
      ['How long does delivery take?', 'From 7 days, counting from the moment the product reaches me.'],
      ['Which languages do you film in?', 'Spanish and English.'],
      ['What can I hire?', 'Two things, and they combine: content I deliver to the brand for its own channels, or a collaboration published on my profiles.'],
      ['What does it cost?', 'It depends on the number of pieces, the versions and subtitles needed, whether it goes out on my profile and whether the brand will use it in paid ads. Write to me and I’ll send a fixed quote.'],
      ['Do you film everything yourself?', 'Almost always. When a campaign needs a more commercial finish, I work with a photographer.'],
      ['What kind of brands?', 'Beauty and skincare above all, plus fashion, fragrance, haircare and lifestyle.'],
    ],
  },
};
